/**
 * Maven iOS Plugin
 * 
 * User: sbott
 * Date: 19.07.2012
 * Time: 19:54:44
 *
 * This code is copyright (c) 2012 let's dev.
 * URL: http://www.letsdev.de
 * e-Mail: contact@letsdev.de
 */

package de.letsdev.maven.plugins.ios.mojo;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

import de.letsdev.maven.plugins.ios.ProjectDeployer;
import de.letsdev.maven.plugins.ios.Utils;


/**
 * 
 * @author let's dev
 * @goal deploy
 * @phase deploy
 */
public class IOSDeployMojo extends AbstractMojo {

	/**
	 * iOS Source Directory
	 * @parameter
	 * 		property="ios.sourceDir"
	 * 		default-value="src/ios"
	 */
	private String sourceDir;

	/**
	 * HockeyApp Api Token
	 * @parameter
	 * 		property="ios.hockeyAppToken"
	 */
	private String hockeyAppToken;
			
	/**
	 * TestFlight Release Notes
	 * @parameter
	 * 		property="ios.releaseNotes"
	 * 		default-value="Release generated by maven-ios-plugin"
	 */
	private String releaseNotes;
		
	/**
	 * iOS App name
	 * @parameter
	 * 		property="ios.appName"
	 * @required
	 */
	private String appName;	
	
	/**
	 * iOS Deploy IPA Path
	 * @parameter
	 * 		property="ios.deployIpaPath"
	 */
	private String deployIpaPath;

    /**
     * iOS Deploy Icon Path
     * @parameter
     * 		property="ios.deployIconPath"
     */
    private String deployIconPath;

    /**
     * iOS configuration
     * @parameter
     * 		property="ios.configuration"
     * 		default-value="Release"
     */
    private String configuration;

	/**
	 * build id, will be set into info.plist
	 * @parameter
	 * 		property="ios.buildId"
	 */
	private String buildId;

	/**
	 * ipaVersion
	 * @parameter
	 * 		property="ios.ipaVersion"
	 */
	private String ipaVersion;

	/**
	 * defining release task
	 * available options are Release, Testflight & AppStoreUpload
	 *
	 * property can also be set via environment variable RELEASE_TASK
	 *
	 * @parameter
	 * 		property="ios.releaseTask"
	 * 		default-value="Release"
	 */
	private String releaseTask;

	/**
	 * the username for iTunesConnect
	 * @parameter iTunesConnectUsername
	 */
	private String iTunesConnectUsername;

	/**
	 * the password for iTunesConnect
	 * @parameter iTunesConnectPassword
	 */
	private String iTunesConnectPassword;
		
	/**
	* The maven project.
	* 
	* @parameter property="project"
	* @required
	* @readonly
	*/
	protected MavenProject mavenProject;	
	
	/**
	 * 
	 */
	public void execute() throws MojoExecutionException, MojoFailureException {
		try {
			final String targetDir = mavenProject.getBuild().getDirectory();
			final String appDir = mavenProject.getBasedir().getAbsoluteFile() + File.separator + targetDir + File.separator + configuration + "-iphoneos" + File.separator;
			
			Map<String, String> properties = new HashMap<String, String>();
			properties.put(Utils.PLUGIN_PROPERTIES.SOURCE_DIRECTORY.toString(), sourceDir);
			properties.put(Utils.PLUGIN_PROPERTIES.TARGET_DIR.toString(), targetDir);
			properties.put(Utils.PLUGIN_PROPERTIES.APP_NAME.toString(), appName);
			properties.put(Utils.PLUGIN_PROPERTIES.HOCKEY_APP_TOKEN.toString(), hockeyAppToken);
			properties.put(Utils.PLUGIN_PROPERTIES.RELEASE_NOTES.toString(), releaseNotes);
			properties.put(Utils.PLUGIN_PROPERTIES.APP_DIR.toString(), appDir);
			properties.put(Utils.PLUGIN_PROPERTIES.CONFIGURATION.toString(), configuration);
			properties.put(Utils.PLUGIN_PROPERTIES.BUILD_ID.toString(), buildId);
			properties.put(Utils.PLUGIN_PROPERTIES.DEPLOY_IPA_PATH.toString(), deployIpaPath);
			properties.put(Utils.PLUGIN_PROPERTIES.DEPLOY_ICON_PATH.toString(), deployIpaPath);
			properties.put(Utils.PLUGIN_PROPERTIES.IPA_VERSION.toString(), ipaVersion);
			properties.put(Utils.PLUGIN_PROPERTIES.RELEASE_TASK.toString(), releaseTask);
			properties.put(Utils.PLUGIN_PROPERTIES.ITUNES_CONNECT_USERNAME.toString(), iTunesConnectUsername);
			properties.put(Utils.PLUGIN_PROPERTIES.ITUNES_CONNECT_PASSWORD.toString(), iTunesConnectPassword);

			ProjectDeployer.deploy(properties, this.mavenProject);
		} catch (Exception e) {
			System.out.println(e.getMessage());
			throw new MojoExecutionException(e.getMessage());
		}
	}

}
