#!/bin/sh

SCRIPT_LOCATION=$(cd "$(dirname "$0")"; pwd)

ARCHIVE_LOCATION=$1
FRAMEWORK_NAME=$2
IPHONEOS_LOCATION=$3
IPHONEOS_FRAMEWORK_LOCATION=$4
IPHONEOS_FRAMEWORK_PRODUCT_LOCATION=$5

cd $ARCHIVE_LOCATION/Products/Library/Frameworks
zip -r $FRAMEWORK_NAME.zip $FRAMEWORK_NAME
cp $FRAMEWORK_NAME.zip $IPHONEOS_FRAMEWORK_LOCATION.zip

cd $IPHONEOS_LOCATION
unzip $IPHONEOS_FRAMEWORK_LOCATION.zip