#!/bin/sh

SCRIPT_LOCATION=$(cd "$(dirname "$0")"; pwd)

ARCHIVE_LOCATION=$1
PRODUCT_PATH=$2
PRODUCT_NAME=$3
TARGET_PATH=$4
PRODUCT_TARGET_PATH=$5

#echo "ARCHIVE_LOCATION:  ""$ARCHIVE_LOCATION"
#echo "PRODUCT_PATH:  ""$PRODUCT_PATH"
#echo "PRODUCT_NAME:  ""$PRODUCT_NAME"
#echo "TARGET_PATH:  ""$TARGET_PATH"
#echo "PRODUCT_TARGET_PATH:  ""$PRODUCT_TARGET_PATH"


cp -R "$ARCHIVE_LOCATION""/""$PRODUCT_PATH""/""$PRODUCT_NAME" "$TARGET_PATH"
if [ -e "$ARCHIVE_LOCATION""/dSYMs/""$PRODUCT_NAME"".dSYM" ]
then
    echo dSYM exists
    cp -R "$ARCHIVE_LOCATION""/dSYMs/""$PRODUCT_NAME"".dSYM" "$TARGET_PATH"
fi


#cd $ARCHIVE_LOCATION/$PRODUCT_PATH

#zip -r $PRODUCT_NAME.zip $PRODUCT_NAME
#cp $PRODUCT_NAME.zip $PRODUCT_TARGET_PATH.zip

#cd $TARGET_PATH
#unzip -o $PRODUCT_TARGET_PATH.zip